[tool.poetry]
name = "testiis"
version = "0.1.0"
description = ""
authors = ["nick-812 <nik.jeromel@student.um.si>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "1.23.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
